### ISSUE TITLE
Plugin does not Enable

### ISSUE THREAD

**Issue by ValMobile** [mVabo/EnchantedMobs#1]
The plugin does not enable. Here is the error message:

[09:42:35 ERROR]: Error occurred while enabling EnchantedSurvival v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: me/mvabo/enhancedcore/files/PlayerData
        at me.mvabo.enchantedsurvival.EnchantedSurvival.onEnable(EnchantedSurvival.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-350]

**Comment by MissGamerz** [comment]
this is a 1.15 plugin

you are running 1.16.4 Paper..........................................................................................
